# Generated by Django 4.2.5 on 2023-09-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='make',
            field=models.CharField(max_length=120),
        ),
    ]
