# Generated by Django 4.2.5 on 2023-09-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_product_type_alter_product_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWaste_facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EWaste_facility_name', models.CharField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
